import {Quiz} from "./types";
export const demoQuizzes:Quiz[]=[
{id:"berlinmuren",title:"Berlinmurens fald",description:"10 spørgsmål om en af Europas vigtigste begivenheder i nyere tid.",category:"Verden",period:"1950–1999",difficulty:"Let",quiz_type:"Historisk begivenhed",is_daily:true,questions:[
{id:"b1",quiz_id:"berlinmuren",question:"Hvilket år faldt Berlinmuren?",answer_a:"1987",answer_b:"1988",answer_c:"1989",answer_d:"1991",correct_answer:"C",explanation:"Berlinmurens grænseovergange blev åbnet den 9. november 1989.",source:"Det Kgl. Bibliotek / Mediestream",sort_order:1},
{id:"b2",quiz_id:"berlinmuren",question:"Hvilken by blev delt af Berlinmuren?",answer_a:"Warszawa",answer_b:"Berlin",answer_c:"Prag",answer_d:"Budapest",correct_answer:"B",explanation:"Muren delte Øst- og Vestberlin fra 1961 til 1989.",source:"Historisk opslagsværk",sort_order:2},
{id:"b3",quiz_id:"berlinmuren",question:"Hvilken begivenhed forbindes ofte med Berlinmurens fald?",answer_a:"Afslutningen på Den Kolde Krig",answer_b:"Starten på Første Verdenskrig",answer_c:"Cubakrisen",answer_d:"Oprettelsen af FN",correct_answer:"A",explanation:"Murens fald blev et stærkt symbol på afslutningen af Den Kolde Krig.",source:"Historisk opslagsværk",sort_order:3}]},
{id:"maanen",title:"Mennesket på Månen",description:"Hvor meget ved du om Apollo 11 og den første bemandede månelanding?",category:"Videnskab",period:"1950–1999",difficulty:"Let",quiz_type:"Historisk begivenhed",is_weekly:true,questions:[
{id:"m1",quiz_id:"maanen",question:"Hvilket år landede mennesker første gang på Månen?",answer_a:"1967",answer_b:"1968",answer_c:"1969",answer_d:"1970",correct_answer:"C",explanation:"Apollo 11 landede på Månen den 20. juli 1969.",source:"NASA",sort_order:1},
{id:"m2",quiz_id:"maanen",question:"Hvad hed månelanderen på Apollo 11?",answer_a:"Eagle",answer_b:"Columbia",answer_c:"Discovery",answer_d:"Endeavour",correct_answer:"A",explanation:"Månelanderen hed Eagle.",source:"NASA",sort_order:2},
{id:"m3",quiz_id:"maanen",question:"Hvor mange mennesker gik på Månen under Apollo 11?",answer_a:"1",answer_b:"2",answer_c:"3",answer_d:"4",correct_answer:"B",explanation:"To astronauter gik på Månen, mens den tredje blev i kredsløb.",source:"NASA",sort_order:3}]}];